### ISSUE TITLE
[Bug Report] --autoinstall-url not autoinstalling

### ISSUE THREAD

**Issue by antiochtech** [dannf/ubuntu-server-netboot#24]
## Description
`--autoinstall-url` not autoinstalling

## {{ cookiecutter.project_name }} version
0.1.1

## Steps to Reproduce
`./ubuntu-server-netboot --iso ubuntu-20.04.2-live-server-amd64.iso --url http://172.16.1.254:50080/ubuntu-20.04.2-live-server-amd64.iso --autoinstall-url http://172.16.1.254:50080/`

`user-data`:
```
#cloud-config
autoinstall:
  apt:
    geoip: true
    preserve_sources_list: false
    primary:
    - arches: [amd64, i386]
      uri: http://us.archive.ubuntu.com/ubuntu
    - arches: [default]
      uri: http://ports.ubuntu.com/ubuntu-ports
  identity: {hostname: myHost, password: $6$exDY1mhS4KUYCE/2$zmn9ToZwTKLhCw.b4/b.ZRTIZM30JZ4QrOQ2aOXJ8yk96xpcCof0kxKwuX1kqLG/ygbJ1f8wxED22bTL4F46P0,
    realname: myRealName, username: myUsername}
  keyboard: {layout: us, toggle: null, variant: ''}
  locale: en_US
  ssh:
    allow-pw: true
    authorized-keys: []
    install-server: true
  storage:
    layout:
      name: direct
  version: 1
```

## Expected Behavior
installation should finish entirely unattended.

## Actual Behavior
installation begins interactively, starting with language selection.

## More Information
`ubuntu-20.04.2-live-server-amd64.iso`, `user-data` and an empty `meta-data` confirmed accessible.

`ubuntu-installer/pxelinux.cfg/default`:
```
DEFAULT install
LABEL install
  KERNEL casper/vmlinuz
  INITRD casper/initrd
  APPEND root=/dev/ram0 ramdisk_size=1500000 ip=dhcp url=http://172.16.1.254:50080/ubuntu-20.04.2-live-server-amd64.iso autoinstall "ds=nocloud-net;s=http://172.16.1.254:50080/" ---
```
